server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.160.64:3306/geodata?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: boyLen.6886
#    url: jdbc:mysql://192.168.50.102:3306/heima?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
#    username: "root"
#    password: "0000"
  profiles:
    active: dev # 环境
  # 微服务
  application:
    name: geodataservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      config:
        file-extension: yaml # 文件后缀名
      discovery:
        cluster-name: HangZhou

mybatis:
  type-aliases-package: len.cloud02.geodata.gd_service.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS