server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.160.64:3306/cloud01_release?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://39.103.160.64:3306/cloud01?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: boyLen.6886
  application:
    name: blog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  cloud:
#    nacos:
#      server-addr: 124.221.110.115:8848 # nacos服务地址
#      discovery:
#        cluster-name: HangZhou
#      discovery:
#        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
#        ephemeral: false # 是否是临时实例

logging:
  level:
    root: info
    len.cloud01.artifact: debug
  file:
    path: log/cloud-dev.log


geodataservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - paperservice

comment.avatar: /image/icon_little/icon002.png