spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.160.64:3306/cloud01?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: boyLen.6886
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true #可以把 POST 请求转为 DELETE 或 POST 请求



server:
  port: 8082