server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.160.64:3306/cloud01_release?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://39.103.160.64:3306/cloud01?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: boyLen.6886
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: paperservice2
#  cloud:
#    nacos:
#      server-addr: 124.221.110.115:8848 # nacos地址
##      server-addr: localhost:8848 # nacos地址
#      config:
#        file-extension: yaml # 文件后缀名
#      discovery:
#        cluster-name: Beijing
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true #可以把 POST 请求转为 DELETE 或 POST 请求

mybatis:
#  type-aliases-package: len.cloud02.geodata.gd_service.pojo
  configuration:
    map-underscore-to-camel-case: true
